### ISSUE TITLE
Etat des lieux du projet

### ISSUE THREAD

**Issue by franomis** [HomeRobotJarvis/Master#5]
- [ ] demander à Gaudin la carte SD des raspberry et regarder le code jarvis
- [ ] demander à Gaudin le robot, la arduino et récupérer le code de homerobot
- [ ] réunion tout mettre en commun

**Comment by andrianj** [comment]
Voici l'état des lieux du home robot(https://github.com/HomeRobotJarvis/Master/files/508809/ETAT.DES.LIEUX.HOMEROBOT.pdf)

**Comment by M0nkeySan** [comment]
Btw sur l'appli mobile on pourrait rajouter la reconnaissance vocale pour contrôler Jarvis. Vu que la reconnaissance en flux continu relève de l'impossible.
